# Generated by Django 5.2.5 on 2026-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20260510_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysis',
            name='improvements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='strengths',
            field=models.TextField(blank=True),
        ),
    ]
