# Generated by Django 5.2.5 on 2026-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_cvanalysis_improvements_cvanalysis_missing_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysis',
            name='cv_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
